// ==UserScript==
// @name         K4G汉化 - 完整词典
// @namespace    k4g-cn-external-dict
// @version      3.4
// @description  K4G汉化脚本的完整词典，包含所有翻译词条
// @updateTime   2026/5/28 17:48:53
//
// 版本更新规范：
// - 每次新增/修改词条后，必须同步更新本文件头部的 @version 与 @updateTime。
// - @version：按小版本递增（例如 2.0 → 2.1 → 2.2）。
// - @updateTime：使用当前时间（格式：YYYY/M/D HH:mm:ss）。
// - 同时更新主脚本版本号（K4G 汉化.user.js 的 @version），以便 浏览器扩展 检测更新。
// ==/UserScript==

window.K4G_EXTERNAL_DICT = {
  
  // ==================== 1. 导航与界面 ====================
  // 通用导航
  'Search': '搜索',
  'Dashboard': '仪表盘',
  'Library': '库',
  'Orders': '订单',
  'Wallet': '钱包',
  'Affiliate': '联盟',
  'Feedback': '反馈',
  'Account': '账户',
  'Support': '支持',
  'Notifications': '通知',
  'Check all as read': '全部标记为已读',
  'View all notifications': '查看全部通知',
  'Logout': '退出登录',
  'Current balance': '当前余额',
  'Current position': '当前排名',
  
  // 面板/仪表板
  'Overview': '概览',
  '+ New Offer': '+ 新建报价',
  'New Offer': '新建报价',
  'Merchant Services': '商家服务',
  'Merchant News': '商家新闻',
  'Supplier News': '供应商新闻',
  'Merchant Support': '商家支持',
  'My Balance': '我的余额',
  'Operations History': '操作记录',
  'You have no operations yet': '你还没有交易记录',
  'Payouts': '提现',
  'Payout': '提现',
  'Invoices': '发票',
  'Reports': '报表',
  'Account details': '账户详情',
  'Support Center': '支持中心',
  'Tickets': '工单',
  'Support Tickets': '支持工单',
  'Start listing': '开始上架',
  'Become an Affiliate': '成为联盟伙伴',
  'Earn with us': '与我们一起赚钱',

  // ==================== 2. 商家与报价管理 ====================
  // 商家相关
  'Merchant': '商家',
  'MY OFFERS': '我的报价',
  'Inactive': '未激活',
  'Active': '已上架',
  'Reactivate': '重新激活',
  'Archived': '已归档',
  'Archive': '归档',
  'Duplicated offer': '重复报价',
  'DuplicatedOffer': '重复报价',
  'Expired': '过期时间',
  'Sold Out at': '售完时间',
  'Reason': '原因',

  // 报价相关常用
  'Offer ID': '报价ID',
  'Qty': '数量',
  'Price': '价格',
  'Profit': '利润',
  'Selected keys': '已选密钥',
  'Available for sale:': '可售数量：',

  // 报价操作
  'Add offer': '新增报价',
  'Sold offers': '已售完报价',
  'Edit': '编辑',
  'Edit Offer': '编辑报价',
  'Promote offer': '推广报价',
  'Boost offer': '提升报价',
  'View Stock': '查看库存',
  'Preview': '预览',
  'Deactivate': '停用',
  'Go to next step': '下一步',
  
  // 报价状态
  'Denied': '已拒绝',
  'Offer Denied': '报价已拒绝',
  'Sold': '已售完',
  'Active to': '有效期至',
  'Days left': '剩余天数',
  'Position': '排名',
  'Title': '标题',
  
  // 报价筛选与导出
  'Show Filters': '显示筛选',
  'Hide Filters': '隐藏筛选',
  'Offers for export (max. 5000)': '待导出报价（最多5000）',
  'Export': '导出',
  
  // 新建报价页面
  'MERCHANT': '商家',
  'NEW OFFER': '新建报价',
  'INSTANT DELIVERY': '即时发货',
  'Choose Existing Product': '选择已有商品',
  'Create Brand New Product': '创建全新商品',
  'Visit Product Page': '访问商品页面',
  'Change Product': '更换商品',
  'Enter product name': '输入商品名称',
  'KEY': '密钥类型',
  'Key': '密钥',
  'Keys': '密钥',
  'Keys not provided for activating order': '未提供激活报价所需的密钥',
  'No keys found': '未找到密钥',
  'No key found': '未找到密钥',
  'ACCOUNT': '账号',
  'LANGUAGES': '语言',
  'Language': '语言',
  'Platform': '平台',
  'Region': '地区',
  'Delivery type': '交付类型',
  'Instant Delivery': '即时发货',
  'Choose option': '选择选项',
  'Hide my offers': '隐藏我的报价',
  
  // 库存管理
  'Stock Details': '库存详情',
  'Faulty stock': '库存有缺陷',
  'Files .csv/.txt': '文件 .csv/.txt',
  'Manual': '手动',
  'Amount:': '数量：',
  'Drop file here': '将文件拖拽到此处',
  'or': '或',
  'Upload from computer': '从电脑上传',
  'Stock': '库存',
  'Pending': '待处理',
  'No offers': '暂无报价',
  'No offers found': '未找到报价',
  
  // 价格管理
  'Price Details': '价格详情',
  'I want to receive': '我希望到账',
  'Customer price': '客户价格',
  'Check the price range on K4G.com': '查看 K4G.com 上的价格区间',
  'Lowest price': '最低价格',
  'Highest price': '最高价格',
  'Dynamic pricing': '动态定价',
  'Default dynamic pricing': '默认动态定价',
  'Apply dynamic pricing': '应用动态定价',
  'Allow manual pricing': '允许人工调价',
  'My minimum price': '我的最低价格',
  'Apply global dynamic pricing': '应用全局动态定价',
  'Apply dynamic pricing for offers:': '应用动态定价到报价：',
  'The percentage entered here will be applied only to your new offers with Dynamic Pricing enabled during the offer creation. This serves as your allowable selling price range. We cannot lower the price beyond the percentage you specify, but we can raise it to increase your profit': '此处输入的百分比仅会在创建报价时应用到开启“动态定价”的新报价，用于限定你的可售价格区间。我们不会把价格降到你指定百分比之外，但可以上调以提高你的利润。',
  
  // 报价详情
  'Offer Details': '报价详情',
  'Sale duration': '销售时长',
  '30 days': '30天',
  '90 days': '90天',
  '365 days': '365天',
  'Automatically reactivate when expired': '过期后自动重新上架',

  // ==================== 3. 账户与设置 ====================
  'Fragments': '碎片',
  'Rewards': '奖励',
  'Currency': '货币',

  // ==================== 4. 客服与支持 ====================
  // 客服相关
  'LiveChat availability': '在线客服可用性',
  'Dear Supplier': '尊敬的供应商',
  'Dear Partner,': '尊敬的合作伙伴：',
  'Thank you for your reply': '感谢您的回复',
  'Thank you for your brief reply': '感谢您的简短回复',
  'Dear customer service team, your email account is now working normally. You can log in again to obtain the verification code and change your information.': '尊敬的客服团队，您的邮件账户现已正常工作。您可以重新登录以获取验证码并修改您的信息。',
  'As per your request, we will refund the Buyer': '应您的请求，我们将向买家退款',
  'Kindly proceed with issuing a full refund to the customer': '请立即为顾客办理全额退款。',
  'As per your request, we will forward the information to the Buyer. Once we receive any update from him, we will immediately let you know.': '应您的请求，我们会将信息转达给买家。一旦收到他的任何更新，我们会立即通知您。',
  'As per your request, we will forward the replacement key to the Buyer': '应您的请求，我们会将补发密钥转交给买家。',
  'K4G Weekly Products Newsletter': 'K4G 每周产品通讯',
  'Below you’ll find a quick overview of upcoming product releases scheduled for this week': '以下是本周计划上线产品的简要概览。',
  'Upcoming Releases This Week': '本周即将上线的产品',
  'If you have any questions regarding these launches or need additional materials, feel free to reach out.': '如果您对这些上线安排有任何疑问，或需要更多资料，请随时联系。',
  'More updates coming next week': '下周将带来更多更新',
  'Your response was sent. We’ll refresh the view when new messages appear': '您的回复已发送。有新消息时我们将刷新视图。',
  'Kind regards': '此致敬礼',
  'Best regards': '此致问候',
  'Complaint regarding sold product': '关于已售商品的投诉',
  'Complaint About Sold Product': '关于已售商品的投诉',
  'Dear Support Team': '尊敬的支持团队',
  'Question regarding sold product': '关于已售商品的问题',
  'Question general': '一般问题',
  'General question': '一般问题',
  'Last reply': '最后回复',
  'Ticket ID': '工单编号',
  'Awaiting': '待处理',
  
  // 工单操作
  'View all': '查看全部',
  'Select template': '选择模板',
  'Refund_approved': '退款已批准',
  'Replacement': '补发',
  'Send message': '发送消息',
  'Write your message': '请输入消息',
  'FROM:': '来自：',

  // 工单管理
  'Create Ticket': '创建工单',
  'All': '全部',
  'Ongoing': '进行中',
  'Open': '待处理',
  'Closed': '已关闭',
  'Solved': '已解决',
  'On Hold': '挂起',
  'No tickets found': '未找到工单',

  // ==================== 5. 营销与推广 ====================
  'Offer exposure': '报价曝光',
  'Sales insights': '销售洞察',
  'Additional Services': '附加服务',
  'Recommended Offer': '推荐报价',
  'Buy now': '立即购买',
  'Promotion Details': '推广详情',
  'Free price changes': '免费价格调整',
  'Want to generate more sales': '想要生成更多销量',
  'Learn more': '了解更多',

  'Search bar': '搜索栏',
  'Highlighted Offer': '高亮报价',
  'Offer for you': '专属报价位',
  'Quests': '任务',

  'Things to do': '待办事项',
  'offers low on stock': '库存不足的报价',
  'offers with low position': '排名靠后的报价',
  'inactive offers': '未激活的报价',
  'offers with unchanged price': '价格未变更的报价',
  'Ongoing cases': '进行中的工单',

  'Rating': '评分',
  'Positive feedback': '好评数',
  'Completed orders': '已完成订单',
  'Complaint ratio': '投诉率',
  'Feedback Received': '收到的反馈',
  'You have no feedback yet': '你还没有收到反馈',

  'Items count': '商品数量',
  'This week': '本周',
  'From': '从',
  'Bestsellers': '畅销商品',
  'Show': '显示',
  'Sort by': '排序方式',
  'Product': '商品',
  'Count': '数量',
  'Revenue': '营收',

  // ==================== 6. 财务与交易 ====================
  'You made a sale!': '你成交了一笔！',
  'Operation': '交易',
  'Operations for export (max. 5000)': '待导出交易记录（最多5000条）',
  'Operation Type': '交易类型',
  'Amount': '金额',
  'Sale': '售出',
  'Complete': '完成',
  'Order ID': '订单ID',
  'Scheduled at': '交易时间',
  'Buyer Country': '买家国家/地区',
  'Amount paid (Sales price)': '实付金额（销售价）',
  'Service Fee': '服务费',
  'KPP Fee': 'KPP费用',
  'Extra Services Fee': '附加服务费',
  'Discount Fee': '折扣费用',
  'Transaction amount': '交易金额',
  'Process date': '处理日期',
  'Schedule date': '计划日期',
  'Type': '类型',
  'Credit memo': '贷项通知单',
  'Payout fee': '提现手续费',
  'Manual K4G balance': '手动K4G余额调整',
  'Offer activation': '报价激活',
  'Offer activated successfully': '报价激活成功',
  'Offer saved successfully': '报价保存成功',
  'Offer archived successfully': '报价归档成功',
  'Offer reactivation external': '报价重新激活（外部）',
  'Price change': '价格变更',
  'Order refund': '订单退款',
  'Refund': '退款',
  'Order spent': '订单支出',
  'K4G commission': 'K4G佣金',
  'Dispute fee': '争议处理费',
  'Refund fee': '退款手续费',
  'Undelivered key fee': '未交付密钥费用',
  'Bad review fee': '差评费用',
  'Refund for resold key': '转售密钥退款',
  'Reward for review': '评价奖励',
  'Refund for undelivered key': '未交付密钥退款',
  'Offer promotions and extra services': '报价推广与附加服务',
  'Other adjustments': '其他调整',
  'K4G Coin': 'K4G币',
  'PayPal Account Fee': 'PayPal账户费用',
  'Balance Expiration': '余额过期',
  'Exchange K4G balance': '兑换 K4G 余额',
  'Exchange K4G balance for a discount code': '将 K4G 余额兑换为折扣码',
  'Your K4G Balance': '你的 K4G 余额',
  'K4G balance': 'K4G 余额',
  'Available Balance': '可用余额',
  'Pending balance': '待结算余额',
  'Amount that remains pending. It will become Available Balance after the review period.': '仍处于待结算状态的金额。审核期结束后将转为可用余额。',
  'Amount that can not be paid out. Can be used to pay for orders. Learn more.': '无法提现的金额，可用于支付订单。了解更多。',
  'Each voucher is valid for 60 days. It cannot be used to purchase K4G coins or gift cards, and the maximum cart value when using the voucher is €15.': '每张代金券有效期为 60 天。代金券不能用于购买 K4G 币或礼品卡，使用代金券时购物车最高金额为 €15。',
  'Refund in money after balance exchange is not available.': '余额兑换后不支持现金退款。',
  'Exchange for a discount code': '兑换折扣码',
  'My Vouchers': '我的代金券',
  'Vouchers': '代金券',
  'You have no vouchers yet': '你还没有代金券',
  'Fragment Sale': '碎片售出',
  'Currency Conversion (out)': '货币转换（转出）',
  'Currency Conversion (in)': '货币转换（转入）',
  'Voucher': '代金券',
  'Completed': '已完成',
  'Canceled': '已取消',
  'No operations found': '未找到交易记录',
  'Expand all': '展开全部',
  'Show less': '收起',
  'Create date': '创建日期',

  // == 常用与零散词条 ==
  'Suppliers Team': '供应商团队',
  'Add and create another offer': '添加并创建另一个报价',
  'Add my Offer': '添加我的报价',

  // 常用属性与操作
  'Add date': '添加日期',
  'Added at': '添加时间',
  'Created at': '创建时间',
  'Batch Id': '批次号',
  'Item batch': '商品批次',
  'COPY': '复制',
  'Clear': '清除',
  'Copied to clipboard': '已复制到剪贴板',
  'Created date': '创建日期',
  'Creation time': '创建时间',
  'Custom': '自定义',
  'Date': '日期',
  'Start date': '开始日期',
  'End date': '结束日期',
  'Period': '周期',
  'Month': '月份',
  'Disable': '禁用',
  'Dispatched': '已发货',
  'Download': '下载',
  'Download and remove': '下载并移除',
  'E-mail Address': '邮箱地址',
  'Edit offer': '编辑报价',
  'Filter': '筛选',
  'Get more sales': '获得更多销量',
  'Delete All Keys': '删除全部密钥',
  'Delete Keys': '删除密钥',
  'Received': '已收到',
  'Remove': '移除',
  'The key was removed correctly': '该密钥已成功移除',
  'Reserved': '已预留',
  'SALES': '销售',
  'Save offer': '保存报价',
  'Select all': '全选',
  'Select all visible': '选择当前可见项',
  'Sold at': '售出时间',
  'Sold date': '售出日期',
  'Status': '状态',
  'Submitted': '已提交',
  'Subscribe': '订阅',
  'Subscribe us': '订阅我们',
  'Unchanged price since': '自以下时间起价格未变',
  'Your search phrase': '你的搜索词',
  'Yes': '是',
  'No': '否',
  'Confirm': '确认',
  'I acknowledge': '我已知晓',
  'Cancel': '取消',
  'Create Account': '创建账户',
  'Connect via': '连接方式',
  'Not a member yet': '还不是会员',
  'Forgot Password': '忘记密码',
  'Log in to your account': '登录您的账户',
  'Remember me': '记住我',
  'Back to Homepage': '返回首页',
  'Log In': '登录',
  'Submit': '提交',
  'Active from / to': '有效期限：从 / 至',
  'Register': '注册',

  // ==================== 7. 长句、复杂文案与规则说明 ====================
  'If you have more products to add at once, please contact our': '如果你有更多商品需要一次性添加，请联系',
  'By creating this offer you agree to': '创建该报价即表示你同意',
  'This is the exact amount that will be transferred to you after all platform fees have been deducted. (customer price minus platform fees and services). Note that if there are VAT rates applied on your account, this amount will change according to the VAT table in use:': '这是在扣除所有平台费用后将实际转给你的金额（客户价格减去平台费用和服务费）。请注意，如果你的账户适用了增值税税率，该金额会根据当前使用的增值税表发生变化：',
  'This amount represents your gross sales price to end customers before platform fees are deducted.': '该金额表示在扣除平台费用之前，你面向终端客户的含税销售价格。',
  'Note that if there are VAT rates applied on your account, this sales price will change according to the VAT table in use:': '请注意，如果你的账户适用了增值税税率，该销售价格会根据当前使用的增值税表发生变化：',
  'The sales price for the end customers also depends on additional services that the customer may choose during the purchase.': '终端客户的销售价格也会受到客户在购买时选择的附加服务影响。',
  'A complete list of gross sales prices can be found in the monthly sales report.': '完整的含税销售价格列表可在每月销售报表中查看。',
  'Set your Minimum Price (Customer price) for which you are willing to sell the key.': '设置你愿意出售该 Key 的最低价格（客户价）。',
  "Turn on the 'Decreasing Price Automatically' to keep your offer on the 1 position as long as possible.": '开启"自动降价"可让你的报价尽可能长时间保持在第1位。',
  "Turn on the 'Decreasing Price Automatically' to keep your offer on the 1 position for as long as possible.": '开启"自动降价"可让你的报价尽可能长时间保持在第1位。',
  "Turn on the 'Allow manual pricing' to have our Team track and adjust the price dynamically to maximize your sales, revenue and profit based on other markets.": '开启"允许人工定价"后，我们的团队将根据其他市场动态跟踪并调整价格，以最大化你的销量、营收和利润。',
  'This option allows us to manually adjust the price of your offer, above the set Minimal Price.': '此选项允许我们在你设定的最低价格之上，手动调整你的报价价格。',
  'Our Team will raise or lower the price to optimize your revenue and profit based on the market conditions.': '我们的团队会根据市场情况上调或下调价格，以优化你的营收和利润。',
  'Especially important for new releases and bestsellers.': '这对新品和畅销商品尤为重要。',
  'If you want to add new keys into your stock, please go to': '如果你想向库存添加新的密钥，请前往',
  'Preferable key format: Login: XXXX  Password: XXXXX, Email Login: XXXX Email Password: XXXX, Domain: XXXX': '建议密钥格式：登录账号：XXXX  登录密码：XXXXX，邮箱账号：XXXX 邮箱密码：XXXX，域名：XXXX',
  'minimalPrice - This value should be less than or equal to': '最低价格 - 该值应小于或等于',
  'Login from different location detected. Please, check your email address and enter verification code in below to log in.': '检测到来自异地的登录。请检查您的邮箱，并在下方输入验证码以登录。',
  'Please, check your mobile 2FA application and enter the code below to log in.': '请检查您手机上的双重身份验证 (2FA) 应用，并输入下方验证码进行登录。',
  'Provided Two Factor Authentication code is invalid': '提供的双重身份验证代码无效',
  'Two Factor Authentication is required': '需要双重身份验证',
  'Make sure each key is in separate line and contains at least 5 characters.': '请确保每个 Key 独立成行，且长度至少为 5 个字符。',
  'To establish a quick and direct communication with our Suppliers Team, please add us on Microsoft Teams at': '为了与我们的供应商团队建立快速直接的沟通，请在 Microsoft Teams 添加我们：',
  'Contact e-mail for wholesale inquiries:': '批发咨询邮箱：',
  'Thank you for your continued partnership!': '感谢您一直以来的合作！',
  'Level your offer to the Recommended ones, making it the most visible and sticky on the offer list.': '将你的报价升级为推荐报价，使其在报价列表中更显眼并置顶展示。',
  'Only one Supplier can promote the particular offer per day': '每个商品每天仅允许 1 位供应商进行此推广。',
  'Add your offer to the search bar to enhance the visibility of your products': '将你的报价加入搜索栏，提升商品曝光度。',
  'Only two offers can be promoted during the day': '每天最多仅可推广 2 个报价。',
  'Focus attention on your offer by highlighting it with a brighter color.': '通过更亮的颜色高亮你的报价，吸引更多关注。',
  'Only two Suppliers can promote the particular offer per day': '每个商品每天最多仅允许 2 位供应商进行此推广。',
  'Put your offer at the top place and merge with buy button of the product page..': '将你的报价置于顶部，并与商品页购买按钮联动展示。',
  'Only for Software offers': '仅适用于软件类报价',
  'Attract more Customers by promoting your offer and getting additional exposure!': '通过推广你的报价并获得额外曝光，吸引更多客户！',
  'Do you want to additionally promote your offer': '你想额外推广你的报价吗',
  'Want to earn more or boost your sales?': '想赚得更多或提升销量吗？',
  'Check available Quests!': '查看可用任务！',
  'Get K4G news to your inbox': '将 K4G 最新资讯发送到你的邮箱',
  'KYC verification completed successfully. Your account is verified.': 'KYC 验证已成功完成。你的账户已通过验证。',

  // ==================== 8. 边缘提示文案与状态兜底 ====================
  "It's your sales price for customer.": '这是你面向客户的销售价格。',
  'price - This value should not be blank.': '价格 - 此值不能为空。',
  'Please enter the price in the correct format, for example 15.50.': '请输入正确格式的价格，例如 15.50。',
  'duration - This value should not be null.': '时长 - 该值不能为空。',
  'Are you sure you want to continue': '您确定要继续吗？',
  "It seems that you've been lost": '页面好像走丢了',
  'Oooups, no such page has been found': '哎呀，找不到该页面',
  'Oooops, no such page has been found': '哎呀，找不到该页面',
  'Not logged in or token expired.': '未登录或登录凭证已过期。',
  'This account is inactive. Contact customer service for more information.': '该账户未激活。请联系客服了解更多信息。',
  'You have no awaiting feedbacks': '你暂无待处理反馈',
  'You have no orders yet': '你还没有订单',
  'You have no products yet': '你还没有商品',
  'You have no tickets yet': '你还没有工单',
  'You have no offers yet': '你还没有任何报价',
  'Please check your spelling or': '请检查拼写或',
  'cannot be found': '未找到',
  'reset the filters.': '重置筛选条件。',
  'Something went wrong. Try again later': '出错了，请稍后重试。',
  "It seems that you're in": '您似乎位于',
  'Do you want to apply suggested settings': '是否应用建议的设置？',
  'Yes, apply settings': '是，应用设置',

  // ==================== 9. 不常用指南与底部链接 ====================
  'Help': '帮助',
  'How to activate keys': '如何激活密钥',
  'How to buy': '如何购买',
  'K4G Purchase Protection': 'K4G 购买保障',
  'K4G Wholesale': 'K4G 批发',
  'Like TOP deals?': '喜欢超值优惠吗？',
  'Need extra money?': '需要额外收入吗？',
  'Our mission': '我们的使命',
  'Browse some of our best deals': '浏览精选特惠',
  'Privacy Policy': '隐私政策',
  'Product list': '商品列表',
  'About us': '关于我们',
  'Blog': '博客',
  'Contact us': '联系我们',
  'Terms & Conditions': '条款与条件',
  'VIP Terms & Conditions': 'VIP 条款与条件',

  // ==================== 10. 其他兜底类枚举 ====================
  'enum.transaction_type.33': '交易类型33',
  'enum.transaction_type.34': '交易类型34',
  'enum.transaction_type.35': '交易类型35',
  'enum.transaction_type.36': '交易类型36'
};
